unstable_features = true
version = "Two"
edition = "2021"
format_strings = true
format_code_in_doc_comments = true
hex_literal_case = "Lower"
wrap_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
